export enum AppViewState {
    DEFAULT = "DEFAULT",
    ONLOADSUCCESSVIEW = "ONLOADSUCCESSVIEW",
    PRODUCTSVIEW = "PRODUCTSVIEW",
    PRODUCTDETAILSVIEW = "PRODUCTDETAILSVIEW",
    ADDTOCARTSUCCESSVIEW = "ADDTOCARTSUCCESSVIEW",
    CARTVIEW = "CARTVIEW",
    ADDPRODUCTFORMSUCCESSVIEW = "ADDPRODUCTFORMSUCCESSVIEW",
    ADDPRODUCTSUCCESSVIEW = "ADDPRODUCTSUCCESSVIEW"
}